In [1]:
import numpy as np

!['Semana 5 - 01'](Semana5-01.png)

In [2]:
def exercicio01():
    R = [[0,1],[0,3],[1,2],[2,2],[3,0],[3,1],[3,2],[4,3]]
    
    shape = (5, 5)
    M = np.zeros(shape, dtype=bool)
    
    for x,y in R:
        M[x, y] = True
    
    produto = M.dot(M)
    comp = (M == produto).all()
    
    print(f'Matriz M:\n\n{M.astype(int)}\n')
    print(f'Composição M o M:\n\n{produto.astype(int)}\n')
    print(f'R é Transitiva? M o M = M? {comp}')

In [3]:
exercicio01()

Matriz M:

[[0 1 0 1 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 0 0]
 [0 0 0 1 0]]

Composição M o M:

[[1 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 1 1 1 0]
 [1 1 1 0 0]]

R é Transitiva? M o M = M? False


!['Semana 5 exercício 02'](Semana5-02.png)

In [4]:
def exercicio02():
    offset = 5
    Z = list(range(-offset, 0)) + list(range(offset+1))
    zlen = len(Z)
    shape = (zlen, zlen)
    
    # Exercício a
    
    Ma = np.zeros(shape, dtype=bool)
    Ra = [(x,y) for x in Z for y in Z if x <= y]
    for x,y in Ra:
        Ma[x+offset, y+offset] = True
    
    produto = Ma.dot(Ma)
    comp = (Ma == produto).all()
    
    print('===== Exercício a: =====\n')
    print(f'Conjunto Z:\n\n{Z}\n')
    print(f'Relação R:\n\n{Ra}\n')
    print(f'Matriz M:\n\n{Ma.astype(int)}\n')
    print(f'Composição M o M:\n\n{produto.astype(int)}\n')
    print(f'M é Transitiva? M o M = M? {comp}\n\n')
    
    # Exercício b
    
    Mb = np.zeros(shape, dtype=bool)
    Rb = [(x,x ** 2) for x in Z]
    for x,y in Rb:
        Mb[x+offset, int(np.sqrt(y))] = True
    
    produto = Mb.dot(Mb)
    comp = (Mb == produto).all()
    
    print('===== Exercício b: =====\n')
    print(f'Conjunto Z:\n\n{Z}\n')
    print(f'Relação R:\n\n{Rb}\n')
    print(f'Matriz M:\n\n{Mb.astype(int)}\n')
    print(f'Composição M o M:\n\n{produto.astype(int)}\n')
    print(f'M é Transitiva? M o M = M? {comp}')

In [5]:
exercicio02()

===== Exercício a: =====

Conjunto Z:

[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5]

Relação R:

[(-5, -5), (-5, -4), (-5, -3), (-5, -2), (-5, -1), (-5, 0), (-5, 1), (-5, 2), (-5, 3), (-5, 4), (-5, 5), (-4, -4), (-4, -3), (-4, -2), (-4, -1), (-4, 0), (-4, 1), (-4, 2), (-4, 3), (-4, 4), (-4, 5), (-3, -3), (-3, -2), (-3, -1), (-3, 0), (-3, 1), (-3, 2), (-3, 3), (-3, 4), (-3, 5), (-2, -2), (-2, -1), (-2, 0), (-2, 1), (-2, 2), (-2, 3), (-2, 4), (-2, 5), (-1, -1), (-1, 0), (-1, 1), (-1, 2), (-1, 3), (-1, 4), (-1, 5), (0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (2, 2), (2, 3), (2, 4), (2, 5), (3, 3), (3, 4), (3, 5), (4, 4), (4, 5), (5, 5)]

Matriz M:

[[1 1 1 1 1 1 1 1 1 1 1]
 [0 1 1 1 1 1 1 1 1 1 1]
 [0 0 1 1 1 1 1 1 1 1 1]
 [0 0 0 1 1 1 1 1 1 1 1]
 [0 0 0 0 1 1 1 1 1 1 1]
 [0 0 0 0 0 1 1 1 1 1 1]
 [0 0 0 0 0 0 1 1 1 1 1]
 [0 0 0 0 0 0 0 1 1 1 1]
 [0 0 0 0 0 0 0 0 1 1 1]
 [0 0 0 0 0 0 0 0 0 1 1]
 [0 0 0 0 0 0 0 0 0 0 1]]

Composição M o M:

[[1 1 1 1 1 

!['Semana 5 exercício 3'](Semana5-03.png)

In [6]:
def exercicio03():
    A = [0, 1, 2, 3, 4, 5]
    
    lenA = len(A)
    shape = (lenA, lenA)
    
    R = [(a,b) for a in A for b in A if b <= a]
    
    M = np.zeros(shape, dtype=bool)
    I = np.identity(lenA, dtype=bool)
    
    for a,b in R:
        M[a, b] = True
    
    reflex = (I & M == I).all()
    anti = ((M == M.T) == I).all()
    trans = (M.dot(M) == M).all()
    
    print(f'Conjunto A:\n\n{A}\n')
    print(f'Relação R:\n\n{R}\n')
    print(f'Matriz M:\n\n{M.astype(int)}\n')
    print(f'M é Reflexiva? I está incluida em M? {reflex}')
    print(f'M é Anti-simétrica? M é igual à Transposta apenas na diagonal? {anti}')
    print(f'M é Transitiva? M o M = M? {trans}\n')
    print(f'M é uma Relação de Ordem sobre A? {reflex and anti and trans}')

In [7]:
exercicio03()

Conjunto A:

[0, 1, 2, 3, 4, 5]

Relação R:

[(0, 0), (1, 0), (1, 1), (2, 0), (2, 1), (2, 2), (3, 0), (3, 1), (3, 2), (3, 3), (4, 0), (4, 1), (4, 2), (4, 3), (4, 4), (5, 0), (5, 1), (5, 2), (5, 3), (5, 4), (5, 5)]

Matriz M:

[[1 0 0 0 0 0]
 [1 1 0 0 0 0]
 [1 1 1 0 0 0]
 [1 1 1 1 0 0]
 [1 1 1 1 1 0]
 [1 1 1 1 1 1]]

M é Reflexiva? I está incluida em M? True
M é Anti-simétrica? M é igual à Transposta apenas na diagonal? True
M é Transitiva? M o M = M? True

M é uma Relação de Ordem sobre A? True


!['Semana 5 exercício 4'](Semana5-04.png)

In [8]:
def exercicio04():
    X = [1, 2, 3, 4, 5]
    R = [[1, 1], [1, 2], [1, 5], [2, 1], [2, 2], [2, 5], [3, 3], [3, 4], [4, 3], [4, 4], [5, 1], [5, 2], [5, 5]]
    lenX = len(X)
    shape = (lenX, lenX)
    
    M = np.zeros(shape, dtype=bool)
    I = np.identity(lenX, dtype=bool)
    
    for x,y in R:
        M[x-1, y-1] = True
    
    reflex = (I & M == I).all()
    sim = (M == M.T).all()
    trans = (M.dot(M) == M).all()
    
    print(f'Conjunto X:\n\n{X}\n')
    print(f'Relação R:\n\n{R}\n')
    print(f'Matriz M:\n\n{M.astype(int)}\n')
    print(f'M é Reflexiva? I está incluida em M? {reflex}')
    print(f'M é Simétrica? M é igual à Transposta? {sim}')
    print(f'M é Transitiva? M o M = M? {trans}\n')
    print(f'M é uma Relação de Equivalência? {reflex and sim and trans}')

In [9]:
exercicio04()

Conjunto X:

[1, 2, 3, 4, 5]

Relação R:

[[1, 1], [1, 2], [1, 5], [2, 1], [2, 2], [2, 5], [3, 3], [3, 4], [4, 3], [4, 4], [5, 1], [5, 2], [5, 5]]

Matriz M:

[[1 1 0 0 1]
 [1 1 0 0 1]
 [0 0 1 1 0]
 [0 0 1 1 0]
 [1 1 0 0 1]]

M é Reflexiva? I está incluida em M? True
M é Simétrica? M é igual à Transposta? True
M é Transitiva? M o M = M? True

M é uma Relação de Equivalência? True
