In [1]:
import numpy as np

!['Semana 5 - 01'](Semana5-01.png)

In [2]:
def exercicio01():
    R = [[0,1],[0,3],[1,2],[2,2],[3,0],[3,1],[3,2],[4,3]]
    
    shape = (5, 5)
    M = np.zeros(shape, dtype=bool)
    
    for par in R:
        M[par[0], par[1]] = True
    
    produto = M.dot(M)
    comp = (M == produto).all()
    
    print(f'Matriz M:\n\n{M.astype(int)}\n')
    print(f'M o M:\n\n{produto.astype(int)}\n')
    print(f'R é Transitiva? M o M = M? {comp}')

In [3]:
exercicio01()

Matriz M:

[[0 1 0 1 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 0 0]
 [0 0 0 1 0]]

M o M:

[[1 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 1 1 1 0]
 [1 1 1 0 0]]

R é Transitiva? M o M = M? False


!['Semana 5 exercício 02'](Semana5-02.png)

In [4]:
def exercicio02():
    offset = 5
    Z = list(range(-offset, 0)) + list(range(offset+1))
    zlen = len(Z)
    shape = (zlen, zlen)
    
    # Exercício a
    
    Ma = np.zeros(shape, dtype=bool)
    Ra = [(x,y) for x in Z for y in Z if x <= y]
    for par in Ra:
        Ma[par[0]+offset, par[1]+offset] = True
    
    produto = Ma.dot(Ma)
    comp = (Ma == produto).all()
    
    print('===== Exercício a: =====\n')
    print(f'Z:\n\n{Z}\n')
    print(f'R:\n\n{Ra}\n')
    print(f'M:\n\n{Ma.astype(int)}\n')
    print(f'M o M:\n\n{produto.astype(int)}\n')
    print(f'M Transitiva? M o M = M? {comp}\n\n')
    
    # Exercício b
    
    Mb = np.zeros(shape, dtype=bool)
    Rb = [(x,x ** 2) for x in Z]
    for par in Rb:
        Mb[par[0]+offset, int(np.sqrt(par[1]))] = True
    
    produto = Mb.dot(Mb)
    comp = (Mb == produto).all()
    
    print('===== Exercício b: =====\n')
    print(f'Z:\n\n{Z}\n')
    print(f'R:\n\n{Rb}\n')
    print(f'M:\n\n{Mb.astype(int)}\n')
    print(f'M o M:\n\n{produto.astype(int)}\n')
    print(f'M Transitiva? M o M = M? {comp}')

In [5]:
exercicio02()

===== Exercício a: =====

Z:

[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5]

R:

[(-5, -5), (-5, -4), (-5, -3), (-5, -2), (-5, -1), (-5, 0), (-5, 1), (-5, 2), (-5, 3), (-5, 4), (-5, 5), (-4, -4), (-4, -3), (-4, -2), (-4, -1), (-4, 0), (-4, 1), (-4, 2), (-4, 3), (-4, 4), (-4, 5), (-3, -3), (-3, -2), (-3, -1), (-3, 0), (-3, 1), (-3, 2), (-3, 3), (-3, 4), (-3, 5), (-2, -2), (-2, -1), (-2, 0), (-2, 1), (-2, 2), (-2, 3), (-2, 4), (-2, 5), (-1, -1), (-1, 0), (-1, 1), (-1, 2), (-1, 3), (-1, 4), (-1, 5), (0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (2, 2), (2, 3), (2, 4), (2, 5), (3, 3), (3, 4), (3, 5), (4, 4), (4, 5), (5, 5)]

M:

[[1 1 1 1 1 1 1 1 1 1 1]
 [0 1 1 1 1 1 1 1 1 1 1]
 [0 0 1 1 1 1 1 1 1 1 1]
 [0 0 0 1 1 1 1 1 1 1 1]
 [0 0 0 0 1 1 1 1 1 1 1]
 [0 0 0 0 0 1 1 1 1 1 1]
 [0 0 0 0 0 0 1 1 1 1 1]
 [0 0 0 0 0 0 0 1 1 1 1]
 [0 0 0 0 0 0 0 0 1 1 1]
 [0 0 0 0 0 0 0 0 0 1 1]
 [0 0 0 0 0 0 0 0 0 0 1]]

M o M:

[[1 1 1 1 1 1 1 1 1 1 1]
 [0 1 1 1 1 1 1 1 1 1 