In [1]:
import numpy as np

!['Semana 5 - 01'](Semana5-01.png)

In [2]:
def exercicio01():
    R = [[0,1],[0,3],[1,2],[2,2],[3,0],[3,1],[3,2],[4,3]]
    
    shape = (5, 5)
    M = np.zeros(shape, dtype=bool)
    
    for par in R:
        M[par[0], par[1]] = True
    
    produto = M.dot(M)
    comp = (M == produto).all()
    
    print(f'Matriz M:\n\n{M.astype(int)}\n')
    print(f'M o M:\n\n{produto.astype(int)}\n')
    print(f'R é Transitiva? M o M = M? {comp}')

In [3]:
exercicio01()

Matriz M:

[[0 1 0 1 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 0 0]
 [0 0 0 1 0]]

M o M:

[[1 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 1 1 1 0]
 [1 1 1 0 0]]

R é Transitiva? M o M = M? False


!['Semana 5 exercício 02'](Semana5-02.png)

In [4]:
def exercicio02():
    Z = [-3, -2, -1, 0, 1, 2, 3]
    a = [(x,y) for x in Z for y in Z if x <= y]
    zlen = len(Z)
    shape = (zlen, zlen)
    Ma = np.zeros(shape, dtype=bool)
    
    for par in a:
        Ma[par[0]+3, par[1]+3] = True
    
    produto = Ma.dot(Ma)
    comp = (Ma == produto).all()
    
    print('Exercício a:\n')
    print(f'R:\n{a}\n')
    print(f'M:\n{Ma.astype(int)}\n')
    print(f'M o M:\n{produto.astype(int)}\n')
    print(f'M Transitiva? M o M = M? {comp}')

In [5]:
exercicio02()

Exercício a:

R:
[(-3, -3), (-3, -2), (-3, -1), (-3, 0), (-3, 1), (-3, 2), (-3, 3), (-2, -2), (-2, -1), (-2, 0), (-2, 1), (-2, 2), (-2, 3), (-1, -1), (-1, 0), (-1, 1), (-1, 2), (-1, 3), (0, 0), (0, 1), (0, 2), (0, 3), (1, 1), (1, 2), (1, 3), (2, 2), (2, 3), (3, 3)]

M:
[[1 1 1 1 1 1 1]
 [0 1 1 1 1 1 1]
 [0 0 1 1 1 1 1]
 [0 0 0 1 1 1 1]
 [0 0 0 0 1 1 1]
 [0 0 0 0 0 1 1]
 [0 0 0 0 0 0 1]]

M o M:
[[1 1 1 1 1 1 1]
 [0 1 1 1 1 1 1]
 [0 0 1 1 1 1 1]
 [0 0 0 1 1 1 1]
 [0 0 0 0 1 1 1]
 [0 0 0 0 0 1 1]
 [0 0 0 0 0 0 1]]

M Transitiva? M o M = M? True
