In [1]:
import numpy as np

In [2]:
a = np.arange(12)
print(type(a))
a

<class 'numpy.ndarray'>


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
print(a.shape)
a.shape = 3, 4
a

(12,)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
print(a[2])
print(a[2, 1])
print(a[:, 1])

[ 8  9 10 11]
9
[1 5 9]


In [5]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [9]:
from random import random
from time import perf_counter as pc

In [17]:
t0 = pc()
with open('10M-floats.txt', 'a') as fd:
    for i in range(10000000):
        fd.write(str(random()) + '\n')
print(type(fd))
print(pc() - t0)

<class '_io.TextIOWrapper'>
9.448958995000794


In [18]:
t0 = pc()
floats = np.loadtxt('10M-floats.txt')
print(type(floats))
print(pc() - t0)
print(floats[0], floats[-1])

<class 'numpy.ndarray'>
24.726338836999275
0.5083875014727635 0.07915260754638986


In [20]:
t0 = pc()
np.save('10M-floats', floats)
print(pc() - t0)

0.10408141299922136


In [21]:
t0 = pc()
floats2 = np.load('10M-floats.npy', 'r+')
print(type(floats2))
print(pc() - t0)
print(floats2[0], floats2[-1])

<class 'numpy.memmap'>
0.020461160000195378
0.5083875014727635 0.07915260754638986
